Restart of main app
CSSS/csss-site-frontend pull request #11
Opened 2024-06-20 21:38 UTC by micahdbak

2024-06-20 23:11 UTC, Nakul727 approved these changes
Very Nice

2024-07-04 04:37 UTC, EarthenSky requested changes
Looks great! I have many questions for you. 

Only one tiny change. Please harass me after you get it done & I'll approve this before midnight.

2024-07-04 04:37 UTC, EarthenSky commented on src/main/pages/Page.js
> +    <>
what does this empty tag mean / do?

2024-07-04 04:37 UTC, EarthenSky commented on src/main/pages/Home.js
> +      <div className="p-4">
is there a reason for mixing single & double quote or are we just vibing?

2024-07-04 04:37 UTC, EarthenSky commented on src/main/pages/Profile.js
> +  }, []);
When does a `useEffect` get triggered on the profile page?

Also, do you need to await `getUser` in order to actually fall the function in js? In python not using `await` means the coroutine never gets invoked.

2024-07-04 04:37 UTC, EarthenSky commented on src/main/pages/Profile.js
> +  const [user, setUser] = useState(null);
What's the default value for `user`? It looks like both values are probably null, but I'm not sure why the destructuring assignment syntax is being used.

What happens when this page is reloaded; when would `user` not be null?

2024-07-04 04:37 UTC, EarthenSky commented on src/main/pages/NotFound.js
> +          Error 404; Page not found :(<br />
Let's create an issue to make this page more funny \:)

2024-07-04 04:37 UTC, EarthenSky commented on src/main/pages/Profile.js
> +    <Page>
Is this essentially "inheriting" the properties of the `Page` object? How does react want us to compose different objects?

2024-07-04 04:37 UTC, EarthenSky commented on src/main/pages/Page.js
> +        <VSCode.NavLink isInFolder={true} text="tech_fair_24.html" href="/events/2024/techfair" />
If this the nav folder (left bar), where's the minimap? It looks like it's probably implemented completely in raspberry? If so, include a comment or maybe a parameter that's like `minimap=True`, just so people know where to look (& maybe if we wanna turn it off?)

Maybe make this an issue & just insert a TODO with the issue #.

2024-07-04 04:39 UTC, micahdbak commented on src/main/pages/Page.js
> +    <>
Empty tag is to surround a sequence of elements; react doesn't let you have any side-by-side. The empty tag isn't actually anything tho, it doesn't represent a DOM object like a div or anything

2024-07-04 04:40 UTC, micahdbak commented on src/main/pages/Home.js
> +      <div className="p-4">
Slightly vibing, but what I'm doing is single quotes in JS, double quotes in JSX

I.e.:

```js
const string = 'this is JS!';

const jsx = (
    <div className="jsx" />
);
```

2024-07-04 04:40 UTC, micahdbak commented on src/main/pages/Profile.js
> +  }, []);
Hehehehehe

2024-07-04 04:42 UTC, micahdbak commented on src/main/pages/Profile.js
> +  }, []);
Ok, so, useEffect with empty brackets: `[]` means that the function is only called when the page first loads.

The function passed into a useEffect cannot be asynchronous; so, to run asynchronous code from a useEffect, you need to define an async function (getUser), then call it in the non-asynchronous useEffect callback. In JS, calling an asynchronous function without awaiting it lets it complete on its own - but you lost complete access to the return value of it. Here, getUser doesn't return anything, so that's OK

2024-07-04 04:43 UTC, micahdbak commented on src/main/pages/Profile.js
> +  const [user, setUser] = useState(null);
Destructuring is how useStates work - the first item in the array is the actual state variable, the second is the function used to set that variable. What's passed into the useState function is the initial value for the state.

So, user equals null when the page is loaded, but when the user is retrieved from the API, setUser is called and user is populated.

2024-07-04 04:43 UTC, micahdbak commented on src/main/pages/NotFound.js
> +          Error 404; Page not found :(<br />
Agreed!!

2024-07-04 04:45 UTC, micahdbak commented on src/main/pages/Profile.js
> +    <Page>
React does things by composing "components" that change based on the properties passed into them (props), i.e., `<Page prop1={thing} prop2={thing}>...</Page>`, and the children passed into them, i.e., `<Page>{children}</Page>`. The source code in Page.js shows how the page is displayed based on the props + children

2024-07-04 04:46 UTC, micahdbak commented on src/main/pages/Page.js
> +        <VSCode.NavLink isInFolder={true} text="tech_fair_24.html" href="/events/2024/techfair" />
Yeah sure!

And honestly, you know what I've been considering, is moving all of csss-raspberry into a shared components folder in csss-site-frontend. It'll be easier to iterate over the components that way, rather than make a release everytime i change something, which is proving a little annoying.

2024-07-04 04:46 UTC, micahdbak commented on src/main/pages/Page.js
> +        <VSCode.NavLink isInFolder={true} text="tech_fair_24.html" href="/events/2024/techfair" />
The minimap however is entirely implemented in the VSCode.Page component in csss-raspberry, if u wanna see the code there

2024-07-04 06:16 UTC, EarthenSky commented on src/main/pages/Home.js
> +      <div className="p-4">
ooh cool. Please make a wiki page called "style guide" or something, & include this rule there!

2024-07-04 06:34 UTC, EarthenSky commented on src/main/pages/Page.js
> +    <>
ahh, I see, because there are a bunch of elements beside each other here. cool & why react (sob)

2024-07-04 06:36 UTC, EarthenSky commented on src/main/pages/Profile.js
> +  const [user, setUser] = useState(null);
ahhh, i see, okay. Where's the data stored when the page is reloaded & the user state is persisted?

2024-07-04 06:37 UTC, EarthenSky commented on src/main/pages/Page.js
> +import React, { useEffect, useState } from 'react';
is `useEffect` an unused import here, or does it secretly have a purpose?

2024-07-04 06:41 UTC, EarthenSky commented on src/main/pages/Profile.js
> +  }, []);
lovely! so it's like an `onLoad()` function.

2024-07-04 06:42 UTC, EarthenSky commented on src/main/pages/Profile.js
> +      setUser(await helpers.casGetUser());
it looks like `casGetUser` is in the `raspberry` repo. Isn't raspberry for visual react components that we expect to be shared? This seems like something that other repos wouldn't care about, so we'd want to keep it in csss-site-frontend.

2024-07-04 06:47 UTC, EarthenSky commented on src/main/pages/Profile.js
> +    <Page>
Ohh, I didn't know that an object had access to its children. I guess that means you can modify your children to be certain ways, like a blue object, etc.

2024-07-04 06:50 UTC, EarthenSky commented on src/main/pages/NotFound.js
> +          Error 404; Page not found :(<br />
https://github.com/CSSS/csss-site-frontend/issues/12

2024-07-04 06:51 UTC, EarthenSky commented on src/main/pages/Home.js
> +      <div className="p-4">
https://github.com/CSSS/csss-site-frontend/wiki/Style-Guide

2024-07-04 06:53 UTC, EarthenSky commented on src/main/pages/Page.js
> +        <VSCode.NavLink isInFolder={true} text="tech_fair_24.html" href="/events/2024/techfair" />
> you know what I've been considering, is moving all of csss-raspberry into a shared components folder in csss-site-frontend. It'll be easier to iterate over the components that way, rather than make a release everytime i change something, which is proving a little annoying.

I just suggested this in a separate comment! I think it should be this way so people can find code more easily + for better organization as well.

2024-07-04 17:13 UTC, micahdbak commented on src/main/pages/Profile.js
> +  const [user, setUser] = useState(null);
If the page is *reloaded*, it hits the API again. However, as the React app is navigated (even through different pages, cuz hash routing), the user state is maintained - that's the benefit of using a useState. However I could store the retrieved user info in cookies - would you prefer that?

2024-07-04 17:13 UTC, micahdbak commented on src/main/pages/Page.js
> +        <VSCode.NavLink isInFolder={true} text="tech_fair_24.html" href="/events/2024/techfair" />
I can definitely add an attribute, I think it's fair :)

2024-07-04 17:14 UTC, micahdbak commented on src/main/pages/Page.js
> +import React, { useEffect, useState } from 'react';
Oopsies, unused import 😛

2024-07-04 17:16 UTC, EarthenSky commented on src/main/pages/Profile.js
> +  const [user, setUser] = useState(null);
Ah I see, so as the react app is traversed it maintains state using some kind of local storage. Does this mean that leaving & returning to the app will require the data to be fetched again? I think this behaviour is totally okay, just wanting to understand the process correctly.

2024-07-04 17:17 UTC, EarthenSky commented on src/main/pages/Page.js
> +import React, { useEffect, useState } from 'react';
haha no worries

2024-07-04 17:30 UTC, micahdbak commented on src/main/pages/Profile.js
> +      setUser(await helpers.casGetUser());
@EarthenSky talk here!

2024-07-04 17:31 UTC, micahdbak commented on src/main/pages/Profile.js
> +      setUser(await helpers.casGetUser());
So, moving everything into csss-site-frontend will make iterating over PRs much faster. I think it might make people a little more interested in working on the frontend too since it's a little less engineered. ATM, getting csss-raspberry to work with csss-site-frontend required a lot of wacky compilation steps and NPM package magic, that i realize now is a little unnecessary

2024-07-04 17:32 UTC, micahdbak commented on src/main/pages/Profile.js
> +      setUser(await helpers.casGetUser());
Having csss-raspberry is only really useful if there will be other repositories also using csss-raspberry, but the way we designed csss-site-frontend is to hold multiple react apps in it - and those can all use a shared folder instead

2024-07-04 17:32 UTC, micahdbak commented on src/main/pages/Profile.js
> +      setUser(await helpers.casGetUser());
Thoughts?

2024-07-04 17:38 UTC, EarthenSky commented on src/main/pages/Profile.js
> +      setUser(await helpers.casGetUser());
> ATM, getting csss-raspberry to work with csss-site-frontend required a lot of wacky compilation steps and NPM package magic, that i realize now is a little unnecessary

ah, I see. Well, as mentioned before I think it's a good idea to combine them! It's become clear that js deployment can get unnecessarily complicated fast, so let's focus on development speed a bit more than before \:)

2024-07-04 17:39 UTC, EarthenSky commented on src/main/pages/Profile.js
> +      setUser(await helpers.casGetUser());
Make a new PR for combining raspberry

2024-07-04 17:39 UTC, micahdbak commented on src/main/pages/Profile.js
> +      setUser(await helpers.casGetUser());
Yay! Sounds good! OK - but expect this PR to become 10k lines longer.

2024-07-04 17:39 UTC, EarthenSky commented on src/main/pages/Profile.js
> +      setUser(await helpers.casGetUser());
new PR!

2024-07-04 17:39 UTC, EarthenSky commented on src/main/pages/Profile.js
> +      setUser(await helpers.casGetUser());
Let's just merge this now

2024-07-04 17:39 UTC, micahdbak commented on src/main/pages/Profile.js
> +      setUser(await helpers.casGetUser());
I'll try my best to whittle down the size of everything

2024-07-04 17:40 UTC, micahdbak commented on src/main/pages/Profile.js
> +      setUser(await helpers.casGetUser());
yeah ok sure!

2024-07-04 17:40 UTC, micahdbak commented on src/main/pages/Profile.js
> +      setUser(await helpers.casGetUser());
approve it!!

2024-07-04 17:41 UTC, micahdbak commented on src/main/pages/Profile.js
> +      setUser(await helpers.casGetUser());
I'll tackle ur request when i merge raspberry, because then I'll have access to the components

2024-07-04 17:41 UTC, EarthenSky approved these changes
Lets include the requested changes in a new PR

2024-07-04 17:41 UTC, merged