Documents Page...
CSSS/csss-site-frontend pull request #59
Opened 2024-08-18 06:19 UTC by Nakul727

Hey, this is the documents page, really basic just wanted to commit the work that I did. Also, I was working on the affiliates page and wrote some boilerplate code which I committed because why not. Tell me if you want to remove something or just change it completely because I didn't spend too much time on it. Just didn't want to hold the task for too long so that other people can work on it, which might be better. 

<img width="1031" alt="Screenshot 2024-08-17 at 11 14 39 PM" src="https://github.com/user-attachments/assets/ce55430c-6d25-43f7-90d8-0e62db54b790">

2024-08-18 06:21 UTC, Nakul727 commented
I also changed the way footer was exported from the components folder which might cause some merge problems. lmk if you want me to change it back.

2024-08-18 06:26 UTC, Nakul727 commented
Also I think the issue was changed and documents page was assigned to someone else. I already made the page so it will be good if there is no duplicate work. If they already did, then choose the better design :)

2024-08-18 07:06 UTC, EarthenSky requested changes
In terms of style this is lovely & consistent! I notably love the alignment of the documents page.

I think we'll want to add more documents to this page eventually (SFSS documents that are important, constitutions from github, etc...), at which time it would be helpful to store them all in a table (maybe even with sortable columns?!). Same with the affliates page, it might be nice to add a bit of text for each affiliate.

But for now, this is perfect!

2024-08-18 07:06 UTC, EarthenSky commented on src/main/pages/Affiliates.js
> +    image: '/static/files/affiliates/wics.jpg',
I notice these images weren't checked in, I think it would be a good idea to serve these from our repo.

2024-08-18 07:11 UTC, EarthenSky commented
> Also I think the issue was changed and documents page was assigned to someone else. I already made the page so it will be good if there is no duplicate work. If they already did, then choose the better design :)

I'm not sure if you checked in with @micahdbak or myself, but please do next time (& grab the issue by assigning yourself! I think you should have the permissions to do so). If you want a page that someone's already assigned, feel free to ask us too! A lot of the issues haven't been worked on yet, just assigned so people have an idea of what to do.

Ultimately I think this is great, and it luckily seems like @gunmack hadn't started yet, so we're all good with picking your design.

2024-08-18 07:15 UTC, gunmack commented
Looks good, just to confirm I did not start on this

2024-08-18 07:42 UTC, EarthenSky commented on public/static/files/docs/constitution_july2024.pdf
We can use https://raw.githubusercontent.com/CSSS/public-docs/dev-update-constitution-policies/constitutions/Constitution_July_2024.pdf and https://raw.githubusercontent.com/CSSS/public-docs/dev-update-constitution-policies/policies/Policies_July_2024.pdf for the time being.

2024-08-18 08:22 UTC, Nakul727 commented on public/static/files/docs/constitution_july2024.pdf
Sounds good! Will update that.

2024-08-18 08:26 UTC, Nakul727 commented on src/main/pages/Affiliates.js
> +    image: '/static/files/affiliates/wics.jpg',
Yeah, these were just temporary images links that I added for the affiliate page. I wanted to remove the code but decided it's worth keeping just to get some suggestions. I have a cool idea on making the page in a sort of expandable card grid ... will try to implement it soon.

2024-08-18 08:31 UTC, Nakul727 commented
I think it is good to separate the documents and affiliate page issue because I kind of initially told Micah I will do both at the same time. @gunmack if you want to work on the documents page, you can either continue/edit the code or rewrite it with the table format. I can focus on the affiliate page. Lmk what you want to do.

2024-08-18 08:43 UTC, Nakul727 commented
Accidentally closed it 😅

2024-08-18 18:38 UTC, EarthenSky commented on src/main/pages/Affiliates.js
> +    image: '/static/files/affiliates/wics.jpg',
sound good, lovely!

2024-08-19 01:13 UTC, EarthenSky commented
> I think it is good to separate the documents and affiliate page issue

I think what you have is a pretty good first step for both pages! Let’s merge this PR & you can make a new PR for the changes you (or @gunmack) might want to make.

I can fix the two small issues I mentioned later tonight if you haven’t already.

2024-08-20 02:37 UTC, micahdbak reviewed
This is amazing, I'll update the response from Gabe and get this merged

2024-08-20 02:37 UTC, micahdbak commented on src/main/components/Footer.js
> +export const Footer = () => {
Gracias <3

2024-08-20 02:40 UTC, micahdbak commented
(Replaced by https://github.com/CSSS/csss-site-frontend/pull/60)

2024-08-20 02:40 UTC, closed without merging